### ISSUE TITLE
can't monitor address from generate

### ISSUE THREAD

**Issue by athlona64** [tech-bureau/catapult-service-bootstrap#13]
nem2-cli monitor status
Monitoring SCIYLU-XH6N2S-DBH2PQ-F5O4RE-LBYD77-GZOQTM-PMOX using 
Error Error: Invalid URL: /ws
    at WebSocket.initAsClient (/usr/local/lib/node_modules/nem2-cli/node_modules/ws/lib/websocket.js:455:11)
    at new WebSocket (/usr/local/lib/node_modules/nem2-cli/node_modules/ws/lib/websocket.js:62:20)
    at Promise (/usr/local/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/Listener.js:77:38)
    at new Promise (<anonymous>)
    at Listener.open (/usr/local/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/Listener.js:71:16)
    at default_1.execute (/usr/local/lib/node_modules/nem2-cli/build/src/commands/monitor/status.js:43:18)
    at CLI.executeCommand (/usr/local/lib/node_modules/nem2-cli/node_modules/clime/bld/core/cli.js:226:24)
    at CLI.<anonymous> (/usr/local/lib/node_modules/nem2-cli/node_modules/clime/bld/core/cli.js:80:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nem2-cli/node_modules/clime/bld/core/cli.js:4:58)

` verbose: websocket PPSRMJPDX4B7KZJH3RFVCDVQWDSH2O65: disconnected /ws websocket connection`

**Comment by athlona64** [comment]
this is solved i'm must attach flag

like this 

> nem2-cli profile create --network MIJIN_TEST --url http://localhost:3000


but in tutorial without flag.

**Comment by athlona64** [comment]
i found new issue 

when i'm tried run nem2-cli monitor status or conrifmed few time will be show 

` verbose: websocket PPSRMJPDX4B7KZJH3RFVCDVQWDSH2O65: disconnected /ws websocket connection`

**Comment by kaiyzen** [comment]
anything nem2-cli related please post on that project/repo, and/or in the sig-client slack channel
