### ISSUE TITLE
can't monitor status, confirmed and unconfirmed

### ISSUE THREAD

**Issue by athlona64** [tech-bureau/catapult-service-bootstrap#15]
root@ip-172-31-26-96:~# nem2-cli monitor status
Monitoring SB7NNP-4RLI56-DEXSPM-JTIRNJ-X2NFH7-QDOWL3-5ULK using 
Error Error: Invalid URL: /ws
    at WebSocket.initAsClient (/usr/lib/node_modules/nem2-cli/node_modules/ws/lib/websocket.js:455:11)
    at new WebSocket (/usr/lib/node_modules/nem2-cli/node_modules/ws/lib/websocket.js:62:20)
    at Promise (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/Listener.js:77:38)
    at new Promise (<anonymous>)
    at Listener.open (/usr/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/Listener.js:71:16)
    at default_1.execute (/usr/lib/node_modules/nem2-cli/build/src/commands/monitor/status.js:43:18)
    at CLI.executeCommand (/usr/lib/node_modules/nem2-cli/node_modules/clime/bld/core/cli.js:226:24)
    at CLI.<anonymous> (/usr/lib/node_modules/nem2-cli/node_modules/clime/bld/core/cli.js:80:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/nem2-cli/node_modules/clime/bld/core/cli.js:4:58)

**Comment by thaihau** [comment]
i also have the same problem

**Comment by kaiyzen** [comment]
there were issues off and on with websocket setup, seems fine in latest releases, if you see this pop up again please open new issue and/or post in the sig-client and sig-testing groups on slack
