### ISSUE TITLE
Runtime error on a Virtual Machine

### ISSUE THREAD

**Issue by slackale** [tech-bureau/catapult-service-bootstrap#23]
Hello
I'm trying to start the service on a Linux Virtual Machine but I'm getting the following error: 

``store-addresses_1         | /ruby/lib/catapult/addresses.rb:59:in `break_into_sections': Not enough addresses (RuntimeError)
db_1                      | 2019-05-15T13:37:04.200+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
store-addresses_1         |     from /ruby/lib/catapult/addresses.rb:29:in `parse'
store-addresses_1         |     from /ruby/bin/store-addresses-if-needed.rb:20:in `<main>'
db_1                      | 2019-05-15T13:37:04.204+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/dbdata 64-bit host=aaa0e00bc095
db_1                      | 2019-05-15T13:37:04.204+0000 I CONTROL  [initandlisten] db version v4.0.9
generate-raw-addresses_1  | /bin-mount/generate-raw-addresses-if-needed: line 8:     6 Illegal instruction     (core dumped) /catapult/bin/catapult.tools.address --generate=${num_addresses} -n mijin-test > ${raw_addresses_path}``

Software used:
Proxmox 5.4
Ubuntu Server 18.04 LTS Virtual Machine
CPU: 4 cores (2 sockets, 2 cores)
RAM: 8 GB

**Comment by slackale** [comment]
Ok I managed to get rid of these errors by setting CPU type to: "host" but I'm still getting lots of "permission denied" when trying to stop the containers and then starting the service up again, Im pretty sure it has to be related to selinux but not sure hot to fix it.

**Comment by kaiyzen** [comment]
how are you running docker, under a regular or root user?  and assume its same user that it was installed under?
