### ISSUE TITLE
Transaction service Unavailable 503

### ISSUE THREAD

**Issue by kahwooi** [tech-bureau/catapult-service-bootstrap#30]
I started the service successfully, I am able to account info using SDK AccountHttp function, but when I want to announce a transaction, I get error response : `{ statusCode: 503, statusMessage: 'Service Unavailable' }`

Server logs :

```
 { message: 'getaddrinfo EAI_AGAIN api-node-0:7900',
stack: 'ServiceUnavailableError: connection failed\n    at Object.createServiceUnavailableError (/node_modules/catapult-api-rest/_build/server/errors.js:55:44)\n    at Socket.serverSocket.on.on (/node_modules/catapult-api-rest/_build/connection/connectionService.js:65:19)\n    at emitOne (events.js:120:20)\n    at Socket.emit (events.js:210:7)\n    at TCP._handle.close [as _onclose] (net.js:547:12)',
rest-gateway_1_180f2943edd4 |   body: { code: 'ServiceUnavailable', message: 'connection failed' } }
```

**Comment by kahwooi** [comment]
After removing data, the problem is solve.
